import { Link, createFileRoute } from "@tanstack/react-router";
import { ArrowRight, FileText, Sparkles, Upload, Zap } from "lucide-react";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [
    { title: "Video Speed Reader — 上傳影片，三分鐘內拿到逐字稿" },
    { name: "description", content: "Upload your video, get a clean transcript in three minutes. 上傳影片，三分鐘內拿到逐字稿。" },
    { property: "og:title", content: "Video Speed Reader — 上傳影片，三分鐘內拿到逐字稿" },
    { property: "og:description", content: "Upload your video, get a clean transcript in three minutes. 上傳影片，三分鐘內拿到逐字稿。" },
    { property: "og:type", content: "website" },
    { name: "twitter:card", content: "summary_large_image" },
  ]}),
  component: HomePage,
});


function Brand() {
  return <Link to="/" className="flex items-center gap-2.5"><span className="brand-gradient grid size-9 place-items-center rounded-lg font-display text-sm font-bold text-primary-foreground">V</span><span className="font-display text-lg font-semibold">Video Speed Reader</span></Link>;
}

function HomePage() {
  return <main className="relative min-h-screen overflow-hidden bg-background">
    <div aria-hidden className="pointer-events-none absolute inset-0 overflow-hidden"><div className="float-soft absolute -left-48 -top-56 size-[540px] rounded-full bg-primary/20 blur-[120px]"/><div className="absolute -right-52 top-[30rem] size-[600px] rounded-full bg-secondary/15 blur-[130px]"/><div className="absolute bottom-0 left-1/3 size-[480px] rounded-full bg-accent/10 blur-[120px]"/></div>
    <header className="relative z-10 mx-auto max-w-7xl px-4 pt-4 sm:px-6 sm:pt-6"><div className="glass-panel flex items-center justify-between rounded-xl px-4 py-3 sm:px-5"><Brand/><nav className="hidden items-center gap-7 text-sm text-muted-foreground md:flex"><a href="#product" className="hover:text-foreground">Product</a><a href="#workflow" className="hover:text-foreground">Workflow</a><a href="#pricing" className="hover:text-foreground">Pricing</a></nav><div className="flex items-center gap-2"><Button asChild variant="ghost" className="hidden sm:inline-flex"><Link to="/auth">登入 Sign in</Link></Button><Button asChild variant="hero"><Link to="/auth">免費開始 Start free</Link></Button></div></div></header>
    <section id="product" className="relative z-10 mx-auto max-w-5xl px-6 pb-24 pt-24 text-center lg:pt-32">
      <div><h1 className="font-display text-[2.6rem] font-bold leading-[1.05] tracking-tight text-balance sm:text-7xl"><span className="brand-text">Video Speed Reader</span></h1><p className="mt-6 text-[1.125rem] font-medium leading-relaxed text-balance text-foreground sm:text-2xl sm:font-semibold lg:text-3xl">上傳影片，三分鐘內拿到逐字稿。</p><p className="mt-4 text-[0.9375rem] leading-snug text-balance text-muted-foreground sm:text-lg">Upload your video, get a clean transcript in three minutes.</p><div className="mt-9 flex w-full flex-col gap-3 sm:w-auto sm:flex-row sm:justify-center"><Button asChild size="lg" variant="hero" className="w-full sm:w-auto"><Link to="/auth">Get started</Link></Button><Button asChild size="lg" variant="glass" className="w-full sm:w-auto"><Link to="/auth">Sign in / 登入</Link></Button></div><div className="mt-10 grid w-full grid-cols-3 divide-x divide-border border-t border-border pt-8 text-sm text-muted-foreground sm:flex sm:flex-wrap sm:justify-center sm:gap-x-8 sm:gap-y-4 sm:divide-x-0 sm:border-t-0 sm:pt-0"><span className="flex flex-col items-center gap-1 px-1 text-center"><strong className="font-display text-xl text-foreground sm:text-2xl">3 min</strong>average turnaround</span><span className="flex flex-col items-center gap-1 px-1 text-center"><strong className="font-display text-xl text-foreground sm:text-2xl">98.4%</strong>word accuracy</span><span className="flex flex-col items-center gap-1 px-1 text-center"><strong className="font-display text-xl text-foreground sm:text-2xl">40+</strong>languages</span></div></div>
    </section>
    <section id="workflow" className="relative z-10 border-y border-border bg-card/30 py-20"><div className="mx-auto max-w-7xl px-6"><div className="max-w-2xl"><p className="text-xs font-semibold uppercase text-secondary">A shorter path to useful words</p><h2 className="mt-3 font-display text-3xl font-semibold text-balance sm:text-4xl">From raw footage to reusable text.</h2><p className="mt-2 font-display text-base text-balance text-secondary sm:text-lg">從原始影片，到可反覆使用的文字。</p></div><div className="mt-10 grid gap-4 md:grid-cols-3">{[[Upload,"Drop in any video","放入任何影片","Upload a file or paste a link. No trimming or prep required."],[Zap,"We map every word","逐字精準標記","Speakers, punctuation, and timestamps are handled automatically."],[FileText,"Edit and ship","編輯並輸出","Search, refine, and export for articles, notes, captions, or archives."]].map(([Icon,title,zh,copy],i)=>{const I=Icon as typeof Upload;return <article key={title as string} className="glass-panel rounded-xl p-6"><span className="font-mono text-xs text-secondary">0{i+1}</span><I className="mt-8 size-5 text-secondary"/><h3 className="mt-4 font-display text-xl font-semibold text-balance">{title as string}</h3><p className="mt-1 font-display text-sm text-balance text-secondary">{zh as string}</p><p className="mt-2 text-sm leading-6 text-muted-foreground">{copy as string}</p></article>})}</div></div></section>
    <section className="relative z-10 mx-auto max-w-7xl px-6 py-24"><div className="grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><p className="text-xs font-semibold uppercase text-secondary">Made for long-form thinkers</p><h2 className="mt-3 font-display text-3xl font-semibold text-balance sm:text-4xl">One clean source of truth.</h2><p className="mt-2 font-display text-base text-balance text-secondary sm:text-lg">單一且乾淨的文字資料庫。</p></div><div className="divide-y divide-border border-y border-border">{[["Creators","Turn interviews and videos into articles, newsletters, and clip scripts."],["Educators","Create searchable lecture notes and accessible captions without manual cleanup."],["Engineers","Archive demos, design reviews, and technical decisions with exact timestamps."]].map(([name,copy])=><div key={name} className="grid gap-3 py-7 sm:grid-cols-[9rem_1fr]"><strong className="font-display">{name}</strong><p className="text-muted-foreground">{copy}</p></div>)}</div></div></section>
    <section id="pricing" className="relative z-10 mx-auto max-w-5xl px-6 pb-24"><div className="glass-panel grid items-center gap-8 rounded-2xl p-7 sm:p-10 md:grid-cols-[1fr_auto]"><div><Sparkles className="size-5 text-secondary"/><h2 className="mt-4 font-display text-2xl font-semibold text-balance sm:text-3xl">Start with your next recording.</h2><p className="mt-1 font-display text-base text-balance text-secondary sm:text-lg">從你的下一支影片開始。</p><p className="mt-3 text-muted-foreground">Your first 60 minutes are free. No card required.</p></div><Button asChild size="lg" variant="hero"><Link to="/auth">Create free account <ArrowRight/></Link></Button></div></section>
    <footer className="relative z-10 border-t border-border"><div className="mx-auto flex max-w-7xl flex-col items-center justify-between gap-4 px-6 py-8 sm:flex-row"><Brand/><p className="text-sm text-muted-foreground">© 2026 Video Speed Reader · 隱私政策 · 服務條款</p></div></footer>
  </main>;
}