"use client";

import Link from "next/link";
import type { ReactNode } from "react";
import { Archive, Coins, Download, FileText, FolderOpen, Plus, Search, Upload } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { usePageMeta } from "@/lib/use-page-meta";
import { JobStatus, isJobInProgress } from "@/components/JobStatus";
import JobsAutoRefresh from "@/views/JobsAutoRefresh";

/** A row in "Recent projects", prepared on the server from the user's `jobs`. */
export type RecentJob = { id: string; title: string; url: string; detail: string; status: string; progress: number };

function RecentProjects({ jobs }: { jobs: RecentJob[] }) {
  if (jobs.length === 0) {
    return <div className="mt-4 rounded-xl border border-border bg-card/50 p-8 text-center"><p className="font-display text-lg font-semibold">還沒有任何逐字稿</p><p className="mt-1 text-sm text-muted-foreground">貼上影片網址，幾分鐘後就能拿到逐字稿。</p><Button asChild variant="hero" className="mt-5"><Link href="/upload"><Upload/>上傳第一支影片</Link></Button></div>;
  }
  return <div className="mt-4 overflow-hidden rounded-xl border border-border">{jobs.map((job)=><article key={job.id} className="grid grid-cols-[auto_1fr_auto] items-center gap-4 border-b border-border bg-card/50 p-4 last:border-0 hover:bg-surface-bright"><span className="brand-gradient grid size-11 place-items-center rounded-lg font-display text-xs font-bold text-primary-foreground">{job.title.slice(0,2).toUpperCase()}</span><div className="min-w-0"><h3 className="truncate text-sm font-medium" title={job.url}>{job.title}</h3><p className="mt-1 truncate text-xs text-muted-foreground">{job.detail}</p></div><div className="flex items-center gap-2"><JobStatus status={job.status} progress={job.progress}/>{job.status==="done"&&<Button asChild variant="ghost" size="icon" title="下載逐字稿 .txt"><a href={`/api/jobs/${job.id}/transcript`} download={`transcript-${job.id.slice(0,8)}.txt`}><Download/></a></Button>}</div></article>)}</div>;
}

export default function Workspace({ header, balance, jobs, totalJobs }: { header: ReactNode; balance: number; jobs: RecentJob[]; totalJobs: number }){usePageMeta({title:"工作區 — Video Speed Reader",description:"上傳影片，在 Video Speed Reader 管理你的精準逐字稿。"});return <main className="min-h-screen bg-background">{header}<JobsAutoRefresh active={jobs.some((j)=>isJobInProgress(j.status))}/><div className="grid min-h-[calc(100vh-4rem)] md:grid-cols-[240px_1fr]"><aside className="border-b border-border p-4 md:border-b-0 md:border-r"><Button asChild variant="hero" className="w-full"><Link href="/upload"><Plus/>New transcript</Link></Button><nav className="mt-7 space-y-1"><p className="px-3 pb-2 text-xs font-semibold uppercase text-muted-foreground">Library</p><a className="flex items-center gap-3 rounded-lg bg-surface-bright px-3 py-2.5 text-sm" href="#"><FolderOpen className="size-4 text-secondary"/>All projects</a><a className="flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm text-muted-foreground hover:bg-surface-bright" href="#"><FileText className="size-4"/>In progress</a><a className="flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm text-muted-foreground hover:bg-surface-bright" href="#"><Archive className="size-4"/>Archived</a></nav><div className="glass-panel mt-8 rounded-xl p-4"><p className="text-xs text-muted-foreground">點數餘額 · 1 點 = 1 分鐘影片</p><p className={`mt-1 font-display font-semibold ${balance<1?"text-destructive":""}`}>剩餘 <span className="tabular-nums">{balance.toLocaleString()}</span> 點</p><Button asChild variant="outline" size="sm" className="mt-3 w-full"><Link href="/credits"><Coins/>購買點數</Link></Button></div></aside><section className="p-5 sm:p-8 lg:p-10"><div className="mx-auto max-w-5xl"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm text-secondary">Your workspace</p><h1 className="mt-1 font-display text-3xl font-semibold sm:text-4xl">Turn footage into words.</h1></div><Button asChild variant="hero"><Link href="/upload"><Upload/>Upload video</Link></Button></div><div className="glass-panel mt-8 flex items-center gap-3 rounded-xl px-4"><Search className="size-4 text-muted-foreground"/><Input aria-label="Search transcripts" placeholder="Search every transcript…" className="h-12 border-0 shadow-none focus-visible:ring-0"/></div><div className="mt-8 flex items-center justify-between"><h2 className="font-display text-xl font-semibold">Recent projects</h2><Link href="/upload" className="text-xs text-muted-foreground hover:text-foreground">共 {totalJobs} 支影片{totalJobs>jobs.length?" · 查看全部":""}</Link></div><RecentProjects jobs={jobs}/></div></section></div></main>}